Repository likelion-ssu/likelionssu-website-2025, pull requests merged in 2025-02, with the labels that each got.

#2 init: 프로젝트 세팅
  .gitignore
  eslint.config.js
  index.html
  package.json
  public/logo.svg
  src/About/assets/.gitkeep
  src/About/components/.gitkeep
  src/About/constants/.gitkeep
  src/About/index.tsx
  src/About/styles/.gitkeep
  src/About/type/.gitkeep
  src/About/utils/.gitkeep
  src/App.tsx
  src/Home/assets/.gitkeep
  src/Home/components/.gitkeep
  src/Home/constants/.gitkeep
  src/Home/index.tsx
  src/Home/styles/.gitkeep
  src/Home/type/.gitkeep
  src/Home/utils/.gitkeep
  src/Recruit/assets/.gitkeep
  src/Recruit/components/.gitkeep
  src/Recruit/constants/.gitkeep
  src/Recruit/index.tsx
  src/Recruit/styles/.gitkeep
  src/Recruit/type/.gitkeep
  src/Recruit/utils/.gitkeep
  src/Router.tsx
  src/common/styles/GlobalStyles.ts
  src/common/styles/theme.ts
  src/common/types/theme.d.ts
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ❗️First Issue

#3 Init: svgr 설정
  package.json
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ❗️First Issue

#4 Init: prettier, lazy loading & Suspense, ErrorBoundary 설정
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/setting.json
  eslint.config.js
  package.json
  src/App.tsx
  src/Router.tsx
  src/common/components/ErrorBoundary.tsx
  src/common/components/Loading.tsx
  src/common/components/NotFound.tsx
  yarn.lock
Labels: ❗️First Issue

#6 Feat: 리쿠르팅 페이지 레이아웃 및 메인콘텐츠 퍼블리싱
  src/Recruit/assets/Circle.svg
  src/Recruit/assets/part_1.svg
  src/Recruit/assets/part_2.svg
  src/Recruit/assets/part_3.svg
  src/Recruit/assets/part_4.svg
  src/Recruit/assets/skill_1.svg
  src/Recruit/assets/skill_2.svg
  src/Recruit/assets/skill_3.svg
  src/Recruit/components/BodySection.tsx
  src/Recruit/components/QuestionSection.tsx
  src/Recruit/components/TimerSection.tsx
  src/Recruit/constants/index.ts
  src/Recruit/constants/partData.ts
  src/Recruit/constants/skillData.ts
  src/Recruit/constants/stepData.ts
  src/Recruit/index.tsx
  src/common/assets/arrow_down.svg
  src/vite-env.d.ts
Labels: 💡Feature

#9 Feat: 자주묻는 질문 퍼블리싱
  src/Recruit/components/BodySection.tsx
  src/Recruit/components/QuestionSection.tsx
  src/Recruit/constants/questionData.ts
Labels: 💡Feature

#13 Feat : 타이머 퍼블리싱 및 기능 구현
  package.json
  src/Recruit/assets/timer_shadow.svg
  src/Recruit/components/TimerSection.tsx
  src/Recruit/components/TimerSectionActive.tsx
  src/Recruit/index.tsx
  src/common/components/CountDown.tsx
  yarn.lock
Labels: 💡Feature

#15 Style: css theme 디자인 적용
  public/fonts/PretendardVariable.woff2
  public/fonts/SUIT-Variable.woff2
  src/Home/components/MainBtn.tsx
  src/Home/index.tsx
  src/common/components/NotFound.tsx
  src/common/styles/GlobalStyles.ts
  src/common/styles/theme.ts
Labels: 🎨Style

#21 Feat: 상단바, 네비바, 푸터 퍼블리싱
  src/Recruit/components/BodySection.tsx
  src/Recruit/components/TimerSection.tsx
  src/Recruit/components/TimerSectionActive.tsx
  src/Recruit/index.tsx
  src/common/assets/ic_close.svg
  src/common/assets/ic_menu.svg
  src/common/components/CountDown.tsx
  src/common/components/Footer.tsx
  src/common/components/NavBar.tsx
  src/common/components/TopBar.tsx
Labels: 💡Feature

#22 Feat : 리쿠르팅 페이지 스냅 설정
  src/Recruit/components/BodySection.tsx
  src/Recruit/components/QuestionSection.tsx
  src/Recruit/components/TimerSection.tsx
  src/Recruit/components/TimerSectionActive.tsx
  src/Recruit/index.tsx
  src/common/components/TopBar.tsx
Labels: 🎨Style

#27 Feat: 파트별 페이지 퍼블리싱
  package.json
  src/Part/assets/.gitkeep
  src/Part/assets/be.png
  src/Part/assets/bg_effect.png
  src/Part/assets/de.png
  src/Part/assets/fe.png
  src/Part/assets/lion_emoji.png
  src/Part/assets/pm.png
  src/Part/components/.gitkeep
  src/Part/components/Comment.tsx
  src/Part/components/RoleContent.tsx
  src/Part/components/RoleSelector.tsx
  src/Part/components/Session.tsx
  src/Part/constants/.gitkeep
  src/Part/constants/Comment.ts
  src/Part/constants/RoleContents.ts
  src/Part/constants/Session.ts
  src/Part/index.tsx
  src/Part/store/useRoleStore.ts
  src/Part/type/.gitkeep
  src/Router.tsx
  yarn.lock
Labels: 💡Feature

#33 feat: break points 설정
  src/common/styles/media.tsx
Labels: 💡Feature

#36 Feat: 파트별 페이지 - 스크롤 액션, 카드 더보기, 네비게이션 & 푸터 추가
  src/Part/components/Comment.tsx
  src/Part/index.tsx
  src/common/components/NavBar.tsx
Labels: 💡Feature

#41 Feat : 반응형 작업
  src/About/components/AboutUsSection.tsx
  src/About/components/ActivityItem.tsx
  src/About/components/ActivitySection.tsx
  src/About/components/ActivitySectionDesktop.tsx
  src/About/components/ActivitySectionMobile.tsx
  src/About/components/Activity_ImgAnimation.tsx
  src/About/components/TeamSection.tsx
  src/About/components/Team_MemberCard.tsx
  src/About/constants/aboutUsText.ts
  src/About/constants/activityList.ts
  src/About/index.tsx
  src/About/utils/activityImageUtil.ts
  src/About/utils/findActivityType.ts
Labels: 💡Feature, 🎨Style

#47 Feat: 메인 헤더 및 푸터 추가 파트별 페이지 수정 사항 반영
  src/Home/index.tsx
  src/Part/components/Comment.tsx
  src/Part/components/RoleContent.tsx
  src/Part/components/RoleSelector.tsx
  src/Part/components/Session.tsx
  src/Part/constants/Comment.ts
  src/Part/constants/RoleContents.ts
  src/Part/constants/Session.ts
  src/Part/index.tsx
Labels: 💡Feature

#50 Feat: 파트별 페이지 모바일 뷰 및 반응형 대응
  src/Part/components/Comment.tsx
  src/Part/components/RoleContent.tsx
  src/Part/components/RoleSelector.tsx
  src/Part/components/Session.tsx
  src/Part/constants/RoleContents.ts
  src/Part/index.tsx
Labels: 🎨Style

#52 Bug: 타입 에러 해결
  src/Part/components/Comment.tsx
Labels: 🐞Bug

#60 Feat: main 모바일 대응
  src/Home/assets/pc_possible.png
  src/Home/assets/possible.png
  src/Home/assets/reality.png
  src/Home/assets/to.png
  src/Home/components/MainBtn.tsx
  src/Home/index.tsx
  yarn.lock
Labels: 🎨Style

#63 fix: 모바일 url바에 의해 잘리는 이슈 해결
  src/App.tsx
  src/common/hooks/useViewportHeight.ts
  src/common/styles/GlobalStyles.ts
Labels: 🐞Bug

#66 Bug : topbar 고정 안됨 해결
  src/About/components/AboutUsSection.tsx
  src/About/components/ActivitySection.tsx
  src/About/components/TeamSection.tsx
  src/About/index.tsx
  src/Project/Detail/components/ProjectDetailComponent.tsx
  src/Project/Detail/index.tsx
  src/Project/components/ProjectMain.tsx
  src/Recruit/components/BodySection.tsx
  src/common/components/TopBar.tsx
Labels: 🐞Bug

#68 Refactor/recruit 2
  src/Recruit/components/BodySection.tsx
  src/Recruit/components/PartBox.tsx
  src/Recruit/components/QuestionSection.tsx
  src/Recruit/components/TimerSectionActive.tsx
  src/common/components/NavBar.tsx
Labels: 🛠️Refactor, 🎨Style

#69 Feat: 파트별 페이지 디자인 추가 요청 작업
  src/Part/components/Comment.tsx
  src/Part/components/RoleContent.tsx
  src/Part/components/RoleSelector.tsx
  src/Part/components/Session.tsx
  src/Part/constants/Session.ts
  src/Part/index.tsx
Labels: 🎨Style

#74 refactor: Topbar 아이콘 및 height 조정
  src/Recruit/assets/roadmap.png
  src/common/components/TopBar.tsx
Labels: 🎨Style

#76 Refactor : recruit,project 페이지 링크 연결 및 텍스트/레이아웃 수정
  src/Project/Detail/components/ProjectDetailComponent.tsx
  src/Recruit/components/BodySection.tsx
  src/Recruit/components/TimerSectionActive.tsx
  src/Recruit/constants/formlink.ts
  src/Recruit/constants/questionData.ts
Labels: 💡Feature, 🎨Style

#78 Refactor: 상단바 및 네비바 리쿠르팅 버튼 추가
  src/Recruit/components/BodySection.tsx
  src/common/components/NavBar.tsx
  src/common/components/TopBar.tsx
Labels: 🎨Style

#80 Fix: 파트 상태 변경 시 슬릭 인덱스 초기화
  src/Part/components/Comment.tsx
Labels: 🛠️Refactor

#84 fix: 폰트 사이즈 변경
  src/About/components/AboutUsSection.tsx
  src/About/components/TeamSection.tsx
  src/Project/components/ProjectCard.tsx
Labels: 🎨Style

#85 Style: 메인 홈 화면 스타일링 변경
  src/Home/index.tsx
Labels: 🎨Style

#87 fix: 프로젝트 배경 이미지 변경
  src/Project/components/ProjectMain.tsx
Labels: 🎨Style
